### ISSUE TITLE
Docker Compose possible?

### ISSUE THREAD

**Issue by squarism** [cloudimmunity/docker-slim#10]
Our ports and volumes are exposed through docker-compose.  We tried slimming an image using the built image but it didn't work correctly I think because the ports weren't exposed so the profiler couldn't see any traffic.

If docker-compose isn't in the realm of docker-slim, would the steps be something like:

- modify Dockerfile to do what `docker-compose.yml` does (expose/volumes)
- slim the image
- undo the Dockerfile changes or just have two paths

Curious to see if this would work.  It'd be cool if we could slim the images generated by docker-compose.  Or if I could somehow tell docker-slim to build using the docker-compose.yml file.

**Comment by pggsx** [comment]
squarism, I would think that docker-compose.yml are basically for ports and volumes and wouldn't directly affect container space since volumes are basically external mount-points and ports are just ports being open on the box. Since Docker always need a Dockerfile to build the base image, how would docker build from the docker-compose.yml?

**Comment by squarism** [comment]
Afaik, when you use docker-compose you take all the `EXPOSE` and `COPY` out of the Dockerfile and put them into sections in `docker-compose.yml`.  `docker-compose build` is the command that builds the images from both `docker-compose.yml` and `Dockerfile`.

**Comment by pggsx** [comment]
squarism, thanks for the clarification. I haven't used docker-compose tool to build images, I've primarily used the main docker cli (docker build,etc) to build images. Thanks for the info~!

**Comment by etienned** [comment]
I'm also interested in using docker-slim with docker-compose. Why this ticket was closed?

**Comment by dels07** [comment]
Any info on this?

**Comment by kcq** [comment]
You can minify your container images when you use docker-compose with the current version of DockerSlim. The '--expose' and '--network' build command parameters will allow you to connect the temporary container DockerSlim creates to the environment/profile docker-compose creates (e.g., `docker-slim build --expose 80 --network gabimelo-flask-boilerplate_default gabimelo-flask-boilerplate_app`).

Take a look at these examples to see how it's done there:

https://github.com/docker-slim/examples/tree/master/3rdparty/codeship-python-django-todoapp-v2/_dockerslim

https://github.com/docker-slim/examples/tree/master/3rdparty/codeship-python-django-todoapp/_dockerslim

https://github.com/docker-slim/examples/tree/master/3rdparty/gabimelo-flask-boilerplate/_dockerslim

**Comment by thenom** [comment]
This means transposing all the docker-compose config that is used\required during testing\development over to docker-slim when they are already configured and tested using the docker-compose.yml including network, ports, env vars, etc.  Providing a the yml to docker-slim (or some other mechanism) would stop duplication of code\config that would be required for pipelines etc.

In our case the devs run and test locally with the docker compose and then they are used for the build and could also be used with docker-slim to produce the final image.

**Comment by x-private-one** [comment]
@thenom supporting docker-compose configs directly is a great UX feature. Trying to find ways to have this sooner (really hope it can be a part of the next release)... It'll be great because then `docker-slim` can also initialize/control the whole environment and you don't need to do it separately/manually with docker-compose.

**Comment by kcq** [comment]
@thenom supporting docker-compose configs directly is a great UX feature. Trying to find ways to have this sooner (really hope it can be a part of the next release)... It'll be great because then docker-slim can also initialize/control the whole environment and you don't need to do it separately/manually with docker-compose.
